#!/usr/bin/env osascript

on run

  tell application "Spotify"
    set currentTrack to name of current track
    set currentArtist to artist of current track
  end tell
  set query to currentArtist & " " & currentTrack
  do shell script "open 'https://www.youtube.com/results?search_query='" & quoted form of query

end run
