format = """
$directory\
[](fg:#BF616A bg:#B48EAD)\
$git_branch\
[](fg:#B48EAD bg:#5E81AC)\
$time\
[ ](fg:#5E81AC)\
"""

right_format = """
$python\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[directory]
style = "bg:#BF616A"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:#B48EAD"
format = '[ $symbol $branch ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5E81AC"
format = '[ $time ]($style)'

[python]
format = '(\($virtualenv\)) '

