map <buffer> ]] <Plug>(PythonsenseStartOfNextPythonFunction)
map <buffer> ][ <Plug>(PythonsenseEndOfPythonFunction)
map <buffer> [[ <Plug>(PythonsenseEndOfPreviousPythonFunction)
map <buffer> [] <Plug>(PythonsenseStartOfPythonFunction)
map <buffer> ]c <Plug>(PythonsenseStartOfNextPythonClass)
map <buffer> ]C <Plug>(PythonsenseEndOfPythonClass)
map <buffer> [c <Plug>(PythonsenseStartOfPythonClass)
map <buffer> [C <Plug>(PythonsenseEndOfPreviousPythonClass)
